language: go

go:
  - 1.0
  - 1.1
  - tip

before_install:
  - export PATH=/home/travis/gopath/bin:$PATH

install:
  - go get github.com/codegangsta/cli
  - go get github.com/vaughan0/go-ini
  - ./install
